name: ts_5_4_5_zitate_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: BunchBlossoms
      fonts:
      - asset: fonts/BunchBlossoms.ttf
    - family: BeautyMountains
      fonts:
      - asset: fonts/BeautyMountainsPersonalUse-od7z.ttf
